In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

### Pull in data manually from a local csv

In [5]:
##Pull in data manually from a local csv
df1 = pd.read_csv("raw_data_to_compare/ap_dataset_id_119_2025_04_11T17_12_50.csv")
df2 = pd.read_csv("raw_data_to_compare/ap_dataset_id_119_2025_04_15T18_18_27.csv")

In [ ]:
## Clean Data

In [28]:
df1.drop([ 'supply_mmid', 'demand_mmid', 'reference_price',
       'reference_price_version'], axis=1, inplace=True)
df2.drop([ 'supply_mmid', 'demand_mmid', 'reference_price',
       'reference_price_version'], axis=1, inplace=True)

In [29]:
len(df1)==len(df2)

True

In [30]:
df1.vehicle_id.nunique()==df2.vehicle_id.nunique()

True

In [96]:
df1[df1.approval_rate<.5].date.max(), df1[df1.response_rate<.75].date.max()

('2025-04-09', '2025-04-09')

In [37]:
# Step 1: Sort both DataFrames by all columns
df1_sorted = df1.sort_values(by=df1.columns.tolist()).reset_index(drop=True)
df2_sorted = df2.sort_values(by=df2.columns.tolist()).reset_index(drop=True)

# Step 2: Identify differences
diff_mask = df1_sorted != df2_sorted
diff_rows = df1_sorted[diff_mask.any(axis=1)]

# Step 3: Show identifying info
print("Different rows by date and vehicle_id:")
print(diff_rows[['date', 'vehicle_id']])

Different rows by date and vehicle_id:
               date  vehicle_id
0        2024-04-10      203775
1        2024-04-10      213298
3        2024-04-10      260732
7        2024-04-10      289768
11       2024-04-10      335668
...             ...         ...
2580099  2025-04-09     3120753
2580100  2025-04-09     3120766
2580101  2025-04-09     3120769
2580102  2025-04-09     3120837
2580103  2025-04-09     3120864

[1444403 rows x 2 columns]

In [44]:
df1[(df1['date']=='2025-04-09')&(df1['vehicle_id']==3120766)]

,date,vehicle_id,reservation_id,date0,price_local,num_trip_owner,is_low_book_chance_12h,is_utilized,paid_days,is_airport_fee_boolean,...,response_rate,avg_rating,tmv_amt_local,tmv_training_amt,country,gid_country,gid,mmid,msrp_local,vehicle_type
1837802,2025-04-09,3120766,NaN,2025-04-09,65.0,13420.0,False,False,NaN,1,...,NaN,NaN,35216,35216.0,US,US,119,id_119,44500.0,SUV

In [45]:
df2[(df2['date']=='2025-04-09')&(df2['vehicle_id']==3120766)]

,date,vehicle_id,reservation_id,date0,price_local,num_trip_owner,is_low_book_chance_12h,is_utilized,paid_days,is_airport_fee_boolean,...,response_rate,avg_rating,tmv_amt_local,tmv_training_amt,country,gid_country,gid,mmid,msrp_local,vehicle_type
1570728,2025-04-09,3120766,NaN,2025-04-09,65.0,13420.0,False,False,NaN,1,...,1.0,NaN,35216,35216.0,US,US,119,id_119,44500.0,SUV

In [34]:
df1_sorted.head()

,date,vehicle_id,reservation_id,date0,price_local,num_trip_owner,is_low_book_chance_12h,is_utilized,paid_days,is_airport_fee_boolean,...,response_rate,avg_rating,tmv_amt_local,tmv_training_amt,country,gid_country,gid,mmid,msrp_local,vehicle_type
0,2024-04-10,203775,NaN,2024-04-10,132.803455,2086.0,False,False,NaN,1,...,1.00,4.8908,26078,26078.0,US,US,119,id_119,68700.0,Car
1,2024-04-10,213298,NaN,2024-04-10,48.977935,5275.0,False,False,NaN,0,...,1.00,4.7757,13276,13276.0,US,US,119,id_119,31205.0,Car
2,2024-04-10,214445,31360538.0,2024-04-10,44.000000,1560.0,False,True,2.0,1,...,1.00,4.9373,14523,14523.0,US,US,119,id_119,24200.0,Car
3,2024-04-10,260732,NaN,2024-04-10,165.000000,1269.0,False,False,NaN,0,...,1.00,4.8555,43219,43219.0,US,US,119,id_119,94100.0,Car
4,2024-04-10,280572,29602390.0,2024-04-10,34.000000,14181.0,False,True,295.0,0,...,0.96,4.8672,7087,7547.0,US,US,119,id_119,18600.0,Car

In [35]:
df2_sorted.head()

,date,vehicle_id,reservation_id,date0,price_local,num_trip_owner,is_low_book_chance_12h,is_utilized,paid_days,is_airport_fee_boolean,...,response_rate,avg_rating,tmv_amt_local,tmv_training_amt,country,gid_country,gid,mmid,msrp_local,vehicle_type
0,2024-04-10,203775,NaN,2024-04-10,132.803455,2086.0,False,False,NaN,1,...,1.00,4.8908,26078,26078.0,US,US,119,id_119,68700.0,Car
1,2024-04-10,213298,NaN,2024-04-10,48.977935,5275.0,False,False,NaN,0,...,1.00,4.7757,13276,13276.0,US,US,119,id_119,31205.0,Car
2,2024-04-10,214445,31360538.0,2024-04-10,44.000000,1560.0,False,True,2.0,1,...,1.00,4.9373,14523,14523.0,US,US,119,id_119,24200.0,Car
3,2024-04-10,260732,NaN,2024-04-10,165.000000,1269.0,False,False,NaN,0,...,1.00,4.8555,43219,43219.0,US,US,119,id_119,94100.0,Car
4,2024-04-10,280572,29602390.0,2024-04-10,34.000000,14181.0,False,True,295.0,0,...,0.96,4.8672,7087,7547.0,US,US,119,id_119,18600.0,Car

In [40]:
# Step 1: Sort both DataFrames by all columns and reset index
df1_sorted = df1.sort_values(by=df1.columns.tolist()).reset_index(drop=True)
df2_sorted = df2.sort_values(by=df2.columns.tolist()).reset_index(drop=True)

# Step 2: Create a boolean mask of where the values differ
diff_mask = df1_sorted != df2_sorted

# Step 3: Loop over differences to get row, column, and values
differences = []

for row_idx, row in diff_mask.iterrows():
    for col in diff_mask.columns[row]:
        if row[col]:
            differences.append({
                'row': row_idx,
                'column': col,
                'date': df1_sorted.loc[row_idx, 'date'],
                'vehicle_id': df1_sorted.loc[row_idx, 'vehicle_id'],
                'df1_value': df1_sorted.loc[row_idx, col],
                'df2_value': df2_sorted.loc[row_idx, col],
            })

# Step 4: Turn into a DataFrame for easy inspection
import pandas as pd
diff_df = pd.DataFrame(differences)
print(diff_df)

             row          column        date  vehicle_id  df1_value  df2_value
0              0  reservation_id  2024-04-10      203775        NaN        NaN
1              0       paid_days  2024-04-10      203775        NaN        NaN
2              1  reservation_id  2024-04-10      213298        NaN        NaN
3              1       paid_days  2024-04-10      213298        NaN        NaN
4              3  reservation_id  2024-04-10      260732        NaN        NaN
...          ...             ...         ...         ...        ...        ...
3284453  2580103  reservation_id  2025-04-09     3120864        NaN        NaN
3284454  2580103       paid_days  2025-04-09     3120864        NaN        NaN
3284455  2580103   approval_rate  2025-04-09     3120864        NaN        NaN
3284456  2580103   response_rate  2025-04-09     3120864        NaN        NaN
3284457  2580103      avg_rating  2025-04-09     3120864        NaN        NaN

[3284458 rows x 6 columns]

In [41]:
differences = []

for row_idx in range(len(df1_sorted)):
    for col in df1_sorted.columns:
        val1 = df1_sorted.at[row_idx, col]
        val2 = df2_sorted.at[row_idx, col]

        if pd.isna(val1) and pd.isna(val2):
            continue  # both are NaN — treat as equal

        if val1 != val2:
            differences.append({
                'row': row_idx,
                'column': col,
                'date': df1_sorted.at[row_idx, 'date'],
                'vehicle_id': df1_sorted.at[row_idx, 'vehicle_id'],
                'df1_value': val1,
                'df2_value': val2,
            })

diff_df = pd.DataFrame(differences)
print(diff_df)

            row         column        date  vehicle_id     df1_value  \
0            13  approval_rate  2024-04-10      357444      0.969828
1            17  approval_rate  2024-04-10      361309      0.973941
2            24    price_local  2024-04-10      397871    116.004889
3            29  approval_rate  2024-04-10      420496      0.972921
4            44  approval_rate  2024-04-10      517783      0.903226
...         ...            ...         ...         ...           ...
291313  2580096     msrp_local  2025-04-09     3120621  25350.000000
291314  2580099  response_rate  2025-04-09     3120753      0.000000
291315  2580100  approval_rate  2025-04-09     3120766           NaN
291316  2580100  response_rate  2025-04-09     3120766           NaN
291317  2580102  response_rate  2025-04-09     3120837      1.000000

           df2_value
0           0.969957
1           0.974026
2         116.004889
3           0.972973
4           0.904459
...              ...
291313  25450.000000
291314      0.500000
291315      1.000000
291316      1.000000
291317      0.500000

[291318 rows x 6 columns]

In [42]:
len(differences)

291318

In [43]:
len(df1)

2580104

In [47]:
diff_df = pd.DataFrame(differences)
diff_df.to_csv("differences.csv", index=False)

In [49]:
diff_df.tail()

            row         column        date  vehicle_id  df1_value  df2_value
291313  2580096     msrp_local  2025-04-09     3120621    25350.0    25450.0
291314  2580099  response_rate  2025-04-09     3120753        0.0        0.5
291315  2580100  approval_rate  2025-04-09     3120766        NaN        1.0
291316  2580100  response_rate  2025-04-09     3120766        NaN        1.0
291317  2580102  response_rate  2025-04-09     3120837        1.0        0.5

In [57]:
diff_df.column.value_counts()

column
response_rate     147735
approval_rate      97984
price_local        30253
paid_days           8364
msrp_local          5508
avg_rating          1271
num_trip_owner       203
Name: count, dtype: int64

In [64]:
price_comp = diff_df[diff_df['column']=='price_local']
sum(price_comp['df1_value']>price_comp['df2_value']+1), sum(price_comp['df2_value']>price_comp['df1_value']+1)

(6, 4)

In [70]:
price_comp[price_comp['df1_value']>price_comp['df2_value']+.6]

            row       column        date  vehicle_id  df1_value  df2_value
275791  2526755  price_local  2025-04-01     3076345  31.802811  30.110072
277414  2533241  price_local  2025-04-02     3076345  32.200432  29.139733
279161  2539783  price_local  2025-04-03     3076345  31.814379  29.335511
280940  2546438  price_local  2025-04-04     3076345  32.322034  31.108379
282805  2553101  price_local  2025-04-05     3076345  33.182100  31.962515
284650  2559710  price_local  2025-04-06     3076345  31.853750  31.064920
285551  2562009  price_local  2025-04-07     2189790  38.000000  35.680908
290992  2579454  price_local  2025-04-09     3076345  28.454798  27.830791

In [72]:
price_comp[price_comp['df2_value']>price_comp['df1_value']+.6]

            row       column        date  vehicle_id   df1_value   df2_value
272865  2513956  price_local  2025-03-30     3104722   50.000000   51.927153
274104  2519778  price_local  2025-03-31     3052767   45.000000   47.928749
274348  2520542  price_local  2025-03-31     3104722   45.156292   46.236243
275669  2526369  price_local  2025-04-01     3052767   48.273569   49.217783
277283  2532861  price_local  2025-04-02     3052767   49.217783   49.847259
279013  2539394  price_local  2025-04-03     3052767   53.386162   54.040421
281246  2547220  price_local  2025-04-05     1130918   99.987983  100.798308
281437  2547821  price_local  2025-04-05     1728471  106.157076  106.880747
282965  2553476  price_local  2025-04-05     3102354   40.000000   41.000000
282980  2553504  price_local  2025-04-05     3105410   43.000000   45.000000
283135  2553897  price_local  2025-04-06     1130918   95.534278   96.246500
284505  2559325  price_local  2025-04-06     3052767   58.922288   59.639981
288272  2571221  price_local  2025-04-08     2930568   54.606407   55.379438
290336  2577407  price_local  2025-04-09     2877273   45.000000   46.000000

In [82]:
days_comp = diff_df[diff_df['column']=='paid_days']
#days_comp
days_comp[days_comp['df1_value']>days_comp['df2_value']+5]

            row     column        date  vehicle_id  df1_value  df2_value
180046  1940475  paid_days  2025-01-03     2193373      110.0      102.0
180871  1946964  paid_days  2025-01-04     2193373      110.0      102.0
181726  1953440  paid_days  2025-01-05     2193373      110.0      102.0
182598  1959875  paid_days  2025-01-06     2193373      110.0      102.0
183485  1966351  paid_days  2025-01-07     2193373      110.0      102.0
...         ...        ...         ...         ...        ...        ...
290304  2577295  paid_days  2025-04-09     2861022       12.0        5.0
290788  2578908  paid_days  2025-04-09     3039442       72.0       60.0
291073  2579640  paid_days  2025-04-09     3089581       30.0       12.0
291109  2579695  paid_days  2025-04-09     3093942       31.0       22.0
291260  2580014  paid_days  2025-04-09     3114981       31.0        7.0

[295 rows x 6 columns]

In [84]:
days_comp.date.value_counts()

date
2025-04-09    450
2025-04-08    376
2025-04-07    324
2025-04-06    275
2025-04-05    250
             ...
2024-06-25      1
2024-06-26      1
2024-06-27      1
2024-06-28      1
2024-04-10      1
Name: count, Length: 365, dtype: int64